tratamientos = {
    "Apple_scab": "Eliminar hojas infectadas y aplicar fungicidas a base de cobre o azufre.",
    "Black_rot": "Retirar frutas afectadas y usar fungicidas preventivos durante la floración.",
    "Cedar_apple_rust": "Eliminar plantas cercanas de enebro y aplicar fungicidas protectores.",
    "Powdery_mildew": "Podar partes afectadas y aplicar azufre o bicarbonato de potasio.",
    "Cercospora_leaf_spot Gray_leaf_spot": "Evitar el exceso de humedad y aplicar fungicidas a base de clorotalonil o mancozeb.",
    "Common_rust_": "Rotar cultivos y usar variedades resistentes; aplicar fungicidas si es necesario.",
    "Northern_Leaf_Blight": "Eliminar restos de cultivo y aplicar fungicidas preventivos.",
    "Esca_(Black_Measles)": "Podar partes afectadas y evitar el exceso de humedad; no hay cura definitiva.",
    "Leaf_blight_(Isariopsis_Leaf_Spot)": "Eliminar hojas enfermas y mejorar la ventilación del cultivo.",
    "Haunglongbing_(Citrus_greening)": "Eliminar árboles infectados y controlar el vector (psílido asiático).",
    "Bacterial_spot": "Evitar el riego por aspersión y aplicar cobre; usar semillas certificadas.",
    "Early_blight": "Eliminar hojas viejas, rotar cultivos y aplicar fungicidas a base de cobre.",
    "Late_blight": "Evitar el exceso de humedad, eliminar plantas infectadas y usar fungicidas sistémicos.",
    "Leaf_scorch": "Aumentar el riego en épocas de calor y mantener la planta libre de estrés.",
    "Leaf_Mold": "Mejorar ventilación y aplicar fungicidas a base de cobre o clorotalonil.",
    "Septoria_leaf_spot": "Eliminar hojas afectadas y aplicar fungicidas protectores.",
    "Spider_mites Two-spotted_spider_mite": "Lavar las hojas y usar acaricidas o jabón potásico.",
    "Target_Spot": "Rotar cultivos, mejorar ventilación y aplicar fungicidas preventivos.",
    "Tomato_Yellow_Leaf_Curl_Virus": "Eliminar plantas infectadas y controlar la mosca blanca.",
    "Tomato_mosaic_virus": "Eliminar plantas enfermas y desinfectar herramientas; no hay cura directa.",
    "healthy": "La planta está sana; mantener riego, ventilación y fertilización equilibrados."
}
